spring:
  application:
    name: config-server    
  profiles:
    active: local      
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          uri: C:\workspace-BE\config-server\.git
          search-paths: src/main/resources/local,src/main/resources/test
#######################################
eureka:
  instance:
    instance-id:  ${spring.application.name}         
##########################
info:
  app:
   name : ${spring.application.name}
   description: '@project.description@'
   version: '@project.version@'
   java:
    version: '@java.version@'      