server:
  port: 10010
  
spring:
  application:
    name: config-server    
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          uri: C:\workspace-BE\config-server\.git
          search-paths: conffiles
          
eureka:
  client:
    service-url:
      defaultZone: http://10.6.221.129:10003/eureka         